INSERT INTO Departments (Name) VALUES
('Ressources Humaines'),
('Informatique'),
('Marketing'),
('Ventes');

INSERT INTO Position (Name, Authority, DepChef, Salary) VALUES
('Responsable RH', 2, 1, 60000),
('Développeur Senior', 1, 2, 55000),
('Chef de Projet', 3, 3, 70000),
('Chargé de Marketing', 1, 3, 45000),
('Représentant des Ventes', 1, 4, 40000);

INSERT INTO Employee (Name, LastName, Address, Seniority, DepartmentID, PositionID) VALUES
('Alice', 'Dupont', '1 Rue de Paris, 75001 Paris', 5, 2, 1),
('Bob', 'Martin', '12 Avenue des Champs-Élysées, 75008 Paris', 3, 1, 1),
('Carla', 'Bernard', '5 Rue de Rivoli, 75001 Paris', 2, 3, 1),
('David', 'Leroy', '7 Rue de la Paix, 75002 Paris', 1, 1, 1),
('Emma', 'Leclerc', '10 Boulevard Saint-Germain, 75005 Paris', 4, 2, 1),
('Jean', 'Dupont', '10 Rue de Paris, Paris', 5, 3, 1),
('Sophie', 'Martin', '15 Avenue des Champs, Lyon', 3, 1, 1),
('Paul', 'Durand', '25 Boulevard Saint Germain, Marseille', 8, 2, 1),
('Lucie', 'Leroy', '30 Rue de la Republique, Lille', 10, 1, 1),
('Marc', 'Moreau', '1 Place de la Concorde, Nantes', 2, 3, 1),
('Claire', 'Simon', '20 Rue de la Liberte, Nice', 1, 2, 1),
('Julien', 'Benoit', '14 Avenue Victor Hugo, Bordeaux', 12, 1, 1),
('Alice', 'Gauthier', '5 Quai de la Loire, Strasbourg', 4, 3, 1),
('Nicolas', 'Garnier', '12 Rue des Fleurs, Toulouse', 6, 1, 1),
('Elodie', 'Roux', '22 Boulevard des Martyrs, Montpellier', 2, 2, 1),
('Thomas', 'Noel', '17 Rue du Loup, Grenoble', 3, 3, 1),
('Emilie', 'Pires', '8 Rue du Moulin, Rennes', 7, 1, 1),
('Francois', 'Chevalier', '14 Avenue de la Gare, Dijon', 5, 2, 1),
('Celine', 'Leblanc', '25 Rue de la Mer, Caen', 3, 3, 1),
('Antoine', 'Marechal', '5 Rue des Ecoles, Saint Etienne', 11, 2, 1),
('Sabrina', 'Boucher', '18 Rue de lHorloge, Amiens', 2, 1, 1),
('Victor', 'Barbier', '28 Rue des Grands Champs, Reims', 9, 3, 1),
('Camille', 'Langlois', '30 Rue des Erables, Toulon', 4, 2, 1),
('Laure', 'David', '15 Rue des Peupliers, Clermont Ferrand', 6, 1, 1),
('Eric', 'Martinez', '22 Boulevard de la Paix, Angers', 7, 2, 1),
('Juliette', 'Bernard', '21 Rue de lEcole, Paris', 4, 3, 1),
('Nicolas', 'Collet', '14 Avenue de la Liberté, Lyon', 3, 1, 1),
('Fanny', 'Garnier', '30 Boulevard des Arts, Marseille', 6, 2, 1),
('Alex', 'Peyton', '15 Rue de lInspiration, Lille', 9, 3, 1),
('Thomas', 'Riviere', '4 Place du Souvenir, Nantes', 1, 2, 1),
('Marc', 'Boucher', '22 Rue de la Paix, Nice', 2, 1, 1),
('Cecile', 'Gaucher', '17 Avenue des Champs, Bordeaux', 11, 3, 1),
('Estelle', 'Nivet', '11 Rue des Fleurs, Strasbourg', 5, 2, 1),
('Simon', 'Bourgeois', '30 Boulevard du Jardin, Toulouse', 7, 1, 1),
('Luc', 'Lemoine', '10 Rue des Lilas, Montpellier', 2, 3, 1),
('Elise', 'Leroux', '25 Rue de la Source, Grenoble', 3, 2, 1),
('Victor', 'Deschamps', '20 Rue des Vignes, Rennes', 8, 1, 1),
('Gabriel', 'Morin', '5 Rue de la Mer, Dijon', 5, 3, 1),
('Chloe', 'Dufour', '29 Boulevard de la Liberté, Caen', 6, 2, 1),
('Antoine', 'Brun', '14 Rue du Commerce, Saint Etienne', 2, 1, 1),
('Olivier', 'Besson', '17 Rue de la Montagne, Amiens', 7, 1, 1),
('Sophie', 'Marchand', '30 Rue des Chênes, Reims', 3, 1, 1),
('Nina', 'Jourdain', '15 Rue des Hirondelles, Toulon', 4, 2, 1),
('Eric', 'Pichon', '12 Rue des Cerisiers, Clermont Ferrand', 9, 3, 1),
('Alice', 'Gaillard', '20 Avenue du Lac, Angers', 6, 1, 1),
('Léo', 'Charpentier', '8 Rue de la Foret, Tours', 3, 2, 1),
('Charlotte', 'Fabre', '15 Rue des Capucins, Marseille', 5, 1, 1),
('Julien', 'Lacombe', '27 Rue de la Mer, Lyon', 6, 3, 1),
('Marie', 'Barre', '30 Boulevard du Parc, Lille', 7, 2, 1),
('Hugo', 'Giraud', '22 Rue des Forges, Nantes', 1, 1, 1),
('Ines', 'Vasseur', '18 Avenue de la Lumière, Nice', 4, 3, 1),
('Arthur', 'Gillet', '11 Rue de la Joie, Bordeaux', 12, 2, 1),
('Sonia', 'Delaunay', '5 Quai des Rêves, Strasbourg', 3, 1, 1),
('Noah', 'Legendre', '12 Rue des Rosiers, Toulouse', 5, 2, 1),
('Samantha', 'Lefevre', '25 Boulevard des Acacias, Montpellier', 2, 3, 1),
('Raphael', 'Desrosiers', '20 Rue de lAmitié, Grenoble', 3, 1, 1),
('Clara', 'Gaultier', '9 Rue du Bonheur, Rennes', 8, 2, 1),
('Julien', 'Allard', '17 Avenue des Cèdres, Dijon', 5, 1, 1),
('Nadia', 'Vallet', '30 Rue des Lilas, Caen', 3, 3, 1),
('Elisa', 'Martel', '15 Rue de la Nouvelle, Saint Etienne', 4, 2, 1),
('Victor', 'Renaud', '22 Rue des Cœurs, Amiens', 2, 1, 1),
('Lucie', 'Bernard', '1 Rue des Voyageurs, Reims', 7, 3, 1),
('Antoine', 'Lamy', '14 Rue de la Nature, Toulon', 6, 2, 1),
('Adele', 'Blanc', '29 Rue de la Roseraie, Clermont Ferrand', 4, 1, 1),
('Elise', 'Lopez', '5 Boulevard de lHorizon, Angers', 8, 3, 1),
('Gabriel', 'Dufresne', '14 Rue de la Plage, Marseille', 7, 2, 1),
('Chloe', 'Caron', '20 Boulevard de la Lune, Lyon', 5, 1, 1),
('Lucas', 'Guillot', '1 Rue de lEspace, Lille', 6, 3, 1),
('Camille', 'Pichon', '9 Rue de la Terre, Nantes', 3, 2, 1),
('Anais', 'Marchal', '15 Rue du Ciel, Nice', 2, 1, 1),
('Maxime', 'Bourdon', '30 Rue des Nuages, Bordeaux', 4, 3, 1),
('Alice', 'Pereira', '17 Rue de la Mer, Strasbourg', 8, 2, 1),
('Lena', 'Delaunay', '22 Rue de la Vallée, Toulouse', 3, 1, 1),
('Thibault', 'Rousseau', '5 Rue des Champs, Montpellier', 5, 2, 1),
('Sophie', 'Marchand', '18 Rue des Pins, Grenoble', 2, 3, 1),
('Clement', 'Leroy', '7 Rue de la Nature, Rennes', 4, 1, 1),
('Juliette', 'Bourgeois', '12 Rue des Fleurs, Dijon', 6, 2, 1),
('Theo', 'Gonzalez', '30 Boulevard des Étoiles, Caen', 5, 1, 1),
('Lise', 'Brunet', '11 Rue des Merveilles, Saint Etienne', 7, 3, 1),
('Hugo', 'Chevalier', '19 Rue des Rencontres, Amiens', 3, 2, 1);